// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjkCYeMv3EaH40tWgheL2CgVsv7o0T8u0',
    appId: '1:365163368504:web:fd69257bdc64e08547d6cd',
    messagingSenderId: '365163368504',
    projectId: 'app-peliculas-aa110',
    authDomain: 'app-peliculas-aa110.firebaseapp.com',
    storageBucket: 'app-peliculas-aa110.firebasestorage.app',
    measurementId: 'G-2N8T35KV98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qTI67ow0R2s5hVXuLKt1TkMgQJ37wPY',
    appId: '1:365163368504:android:b2b9538171b4ff4747d6cd',
    messagingSenderId: '365163368504',
    projectId: 'app-peliculas-aa110',
    storageBucket: 'app-peliculas-aa110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4wUmtdWzMHHaJmbX1h41EckikTuJrAs8',
    appId: '1:365163368504:ios:9d21c8b34985f7fd47d6cd',
    messagingSenderId: '365163368504',
    projectId: 'app-peliculas-aa110',
    storageBucket: 'app-peliculas-aa110.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4wUmtdWzMHHaJmbX1h41EckikTuJrAs8',
    appId: '1:365163368504:ios:9d21c8b34985f7fd47d6cd',
    messagingSenderId: '365163368504',
    projectId: 'app-peliculas-aa110',
    storageBucket: 'app-peliculas-aa110.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationWidgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjkCYeMv3EaH40tWgheL2CgVsv7o0T8u0',
    appId: '1:365163368504:web:a358caea85572a7947d6cd',
    messagingSenderId: '365163368504',
    projectId: 'app-peliculas-aa110',
    authDomain: 'app-peliculas-aa110.firebaseapp.com',
    storageBucket: 'app-peliculas-aa110.firebasestorage.app',
    measurementId: 'G-6MKW5CDM15',
  );
}
